### ISSUE TITLE
Pętla for

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/rpg-procedural#10]
https://github.com/fisheye36/rpg-procedural/blob/db25b4e911d4b8e2872c96dc630c39a08fc13f76/character.cpp#L19

Nie rozumiem dlaczego pętla jest od `i = 1`, a nie od `i = 0`, ale pewnie przeoczyłem coś oczywistego.

W tej pętli zamieniłbym `i < SKILLS_COUNT + 1` na `i <= SKILLS_COUNT`. Chociaż pewnie nie ma to większego znaczenia bo kompilator i tak zoptymalizuje kod.

Tutaj prosi się użyć vectora zamiast gołej tablicy i pętli do zerowania:
```
vector<skill> newCharacter(SKILLS_COUNT + 1, 0);
```

**Comment by fisheye36** [comment]
`newCharacter[0]` to `newCharacter[ID]`, dlatego pętla iteruje od `i = 1`. Co do vectora: starałem się jak najmniej korzystać z jakichkolwiek klas (oprócz oczywiście `cout` i `cin`), stąd użycie tablicy.
