### ISSUE TITLE
Tablica vs vector

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/rpg-procedural#3]
https://github.com/fisheye36/rpg-procedural/blob/db25b4e911d4b8e2872c96dc630c39a08fc13f76/menus.cpp#L15

Generalnie odradzam używanie tablic. Praktycznie zawsze zamiast tablicy lepiej jest użyć wektora. W nowym standardzie są świetne możliwości inicjalizacji i dodawania elementów, więc nie ma problemów z wydajnością. Wektor zawsze daje dodatkowe możliwości, które się przydadzą, np. wbudowana informacja o rozmiarze.
Na zajęciach używają Państwo "gołych" tablic, żeby pomęczyć się ze wskaźnikami i dobrze je opanować, ale jeżeli się da lepiej tego unikać, bo jest to potencjalne źródło błędów. Oczywiście, jeżeli trzeba coś zoptymalizować lub z jakiegoś powodu nie ma innego wyjścia to należy użyć wskaźników.

**Comment by fisheye36** [comment]
Starałem się napisać ten program w jak najbardziej proceduralny sposób i z wektora skorzystałem tylko przy globalnym przechowywaniu statystyk postaci (aby nie bawić się w realokację pamięci itd.). Oczywiście, pisząc coś sam od siebie korzystałbym praktycznie z samych wektorów, gdyż są dużo wygodniejsze i bezpieczniejsze w użyciu.
