### ISSUE TITLE
Bardziej ogólne rozwiązanie

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/rpg-procedural#5]
https://github.com/fisheye36/rpg-procedural/blob/db25b4e911d4b8e2872c96dc630c39a08fc13f76/menus.cpp#L20

W aktualnej wersji, jeżeli będzie Pan chciał dodać nową opcję do menu, np. Wczytaj grę, musi Pan dodać go do `availableOptions` i `switch`. Można by zastanowić się czy nie da się uogólnić obecnego kodu, tak aby łatwiej było dodawać nowe elementy. Na przykład można by utworzyć strukturę (lepiej obiekt), który przechowywałby symbol (literę, którą wybiera użytkownik), opis (tekst wyświetlany na ekranie) i wskaźnik do funkcji, która ma być wywołana, albo obiekt, który będzie wykonywał jakąś akcję (coś w stylu wzorca projektowego polecenie). Wtedy można by utworzyć listę takich obiektów. W funkcji `displayMainMenu` `switch` można zastąpić np. pętlą po wszystkich obiektach i sprawdzaniem czy wybrany przez użytkownika symbol pasuje do jakiejś akcji. Można również utworzyć mapę lub zbiór obiektów z kluczem będącym symbolem wybieranym przez użytkownika. W ten sposób jedyne co trzeba będzie zrobić aby dodać nową opcję to dodać element do listy/zbioru/mapy.

**Comment by fisheye36** [comment]
Oczywiście, że tak ale w zadaniu nie wolno było korzystać ani z klas, ani ze struktur :) Ograniczając się do programowania czysto proceduralnego wydaje mi się, że takie rozwiązanie jest sensowne i czytelne, aczkolwiek rozszerzając menu trzeba byłoby dokonać modyfikacji w aż trzech miejscach: przy `cout`, inicjalizacji `availableOptions` oraz w instrukcji `switch`. Innego wyjścia póki co nie wymyśliłem.
