### ISSUE TITLE
Ten sam schemat wyboru opcji

### ISSUE THREAD

**Issue by GrzegorzGach** [fisheye36/rpg-procedural#7]
https://github.com/fisheye36/rpg-procedural/blob/db25b4e911d4b8e2872c96dc630c39a08fc13f76/fight.cpp#L39

W tym miejscu po raz kolejny powtarza się ten sam schemat kodu, który służy do komunikacji z użytkownikiem. Ładnie byłoby wszędzie gdzie zachodzi komunikacja z użytkownikiem w ten sposób zastąpić wywołaniem tej samej funkcji, ale o wiele lepiej obiektu, który jest konfigurowany w odpowiedni sposób przy pomocy listy dozwolonych akurat opcji. Taka zmiana jednak krzyczy o klasy (i pewnie o dziedziczenie), których jeszcze Państwo nie znają.

**Comment by fisheye36** [comment]
Przy programowaniu czysto proceduralnym nie bardzo da się to uogólnić, ewentualnie mógłbym utworzyć tablicę wskaźników do funkcji, analogicznie jak tablicę `availableOptions` ale dalej niektóre fragmenty kodu by się powtarzały. Poza tym w zależności od wyboru wykonywane są czasami zupełnie inne funkcje (pobierające inne parametry jak i zwracające różne typy danych). Można by pokombinować coś z klasami ale jak wspomniałem wcześniej - w poleceniu był zakaz ich używania.

PS. Ja wiem co to są klasy (w C++ i nie tylko) :)
